exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - "singleton_class#with"
  DataClump:
    exclude:
      - "Lode::Tables::Abstract"
  DuplicateMethodCall:
    exclude:
      - "singleton_class#with"
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - "singleton_class#with"
  ModuleInitialize:
    exclude:
      - "Lode"
  UnusedParameters:
    exclude:
      - "Lode::Tables::Abstract#find"
      - "Lode::Tables::Abstract#primary_id"
      - "Lode::Tables::Abstract#upsert"
